# Generated by Django 4.2.5 on 2024-05-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_takeout_date_trash_take_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
